# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
