# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0003_dailyworklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentilas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_username', models.CharField(max_length=100)),
                ('jira_password', models.CharField(max_length=100)),
                ('basecamp_token', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work_logger_app.UsersAccount')),
            ],
        ),
    ]
