# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0004_credentilas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
