# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0005_usersaccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersaccount',
            name='password',
        ),
    ]
