# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0006_remove_usersaccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworklog',
            name='time_spent',
            field=models.CharField(default='1m', max_length=20),
        ),
    ]
