# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0007_auto_20170507_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentilas',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dailyworklog',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
