# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0008_auto_20170507_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentilas',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work_logger_app.UsersAccount'),
        ),
        migrations.AddField(
            model_name='dailyworklog',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work_logger_app.UsersAccount'),
        ),
    ]
