# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0009_auto_20170507_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
