# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0011_auto_20170507_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworklog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
