# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0012_auto_20170507_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
