# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0013_usersaccount_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentilas',
            old_name='basecamp_token',
            new_name='slack_token',
        ),
    ]
