# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logger_app', '0014_auto_20170513_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworklog',
            name='push_to_jira',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyworklog',
            name='push_to_slack',
            field=models.BooleanField(default=False),
        ),
    ]
